services:
  posyandu:
    container_name: posyandu
    depends_on:
      - posyandu-db
    image: mfathoor/posyandu-api:latest
    networks:
      - posyandu
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    volumes:
      - posyandu:/usr/src/app

  posyandu-db:
    container_name: posyandu_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    image: mysql:5.7
    networks:
      - posyandu
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: on-failure
    volumes:
      - posyandu-db:/var/lib/mysql

volumes:
    posyandu:
    posyandu-db:

networks:
    posyandu:
        driver: bridge
